index:
   path: /
   controller: App\Controller\HomePage\Init::index

resume:
   path: /resume
   controller: App\Controller\Resume\Resume::index

exercises:
   path: /exercises
   controller: App\Controller\Exercises\Exercises::index

bee_war:
   path: /beewar
   controller: App\Controller\BeeWar\BeeWar::index