# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Controller\HomePage\:
        resource: '../src/Controller/HomePage/'
        tags: ['controller.service_arguments']

    App\Controller\BeeWar\:
        resource: '../src/Controller/BeeWar/'
        tags: ['controller.service_arguments']
    
    App\Controller\Resume\:
        resource: '../src/Controller/Resume'
        tags: ['controller.service_arguments']

    App\Controller\Exercises\:
        resource: '../src/Controller/Exercises'
        tags: ['controller.service_arguments']
        # autowire: true
    
    App\Controller\Exercises\Data_Structures:
        autowire: true
    
    App\Controller\BeeWar\BeeWar:
        autowire: true

    App\Controller\BeeWar\Bee:
        autowire: true
    
    App\Controller\BeeWar\Colony:
        autowire: true

    App\Controller\BeeWar\War_Zone:
        autowire: true

    App\Controller\BeeWar\Rules:
        autowire: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
