<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4xRN40Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4xRN40Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4xRN40Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4xRN40Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4xRN40Y\App_KernelDevDebugContainer([
    'container.build_hash' => '4xRN40Y',
    'container.build_id' => 'f09a9fda',
    'container.build_time' => 1602497749,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4xRN40Y');
